/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    peptides: Peptide;
    studies: Study;
    categories: Category;
    partners: Partner;
    'affiliate-links': AffiliateLink;
    'click-events': ClickEvent;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    peptides: PeptidesSelect<false> | PeptidesSelect<true>;
    studies: StudiesSelect<false> | StudiesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'affiliate-links': AffiliateLinksSelect<false> | AffiliateLinksSelect<true>;
    'click-events': ClickEventsSelect<false> | ClickEventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'partner' | 'member';
  /**
   * Determines content access level across the app.
   */
  membershipTier: 'free' | 'researcher' | 'pro';
  /**
   * When the current paid membership period ends.
   */
  membershipExpiresAt?: string | null;
  /**
   * Stripe customer ID for billing management.
   */
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  /**
   * Linked partner account for portal access.
   */
  partnerProfile?: (number | null) | Partner;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  slug: string;
  /**
   * Short description shown to users on the directory page.
   */
  description?: string | null;
  logo?: (number | null) | Media;
  /**
   * Partner home URL (not the affiliate link).
   */
  website: string;
  status: 'active' | 'pending' | 'suspended';
  /**
   * Higher tiers get featured placement and unlock COA upload capability.
   */
  verificationTier?: ('basic' | 'verified' | 'premium') | null;
  acceptedTermsAt?: string | null;
  /**
   * Affiliate commission percentage (e.g. 10 = 10%).
   */
  commissionRate?: number | null;
  contactEmail: string;
  /**
   * Which peptides does this partner supply? Used to auto-generate affiliate links.
   */
  carriedPeptides?: (number | Peptide)[] | null;
  /**
   * Internal notes (admin only).
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "peptides".
 */
export interface Peptide {
  id: number;
  /**
   * Primary/common name (e.g. BPC-157, Thymosin Alpha-1)
   */
  name: string;
  slug: string;
  /**
   * Other names, CAS numbers, or brand names for this peptide.
   */
  aliases?:
    | {
        alias?: string | null;
        id?: string | null;
      }[]
    | null;
  casNumber?: string | null;
  molecularFormula?: string | null;
  /**
   * e.g. 1419.53 Da
   */
  molecularWeight?: string | null;
  categories?: (number | Category)[] | null;
  researchStatus: 'preclinical' | 'phase1' | 'phase2' | 'phase3' | 'approved' | 'discontinued';
  /**
   * Short plain-text summary — visible to all users including free tier.
   */
  summary: string;
  /**
   * Detailed molecular mechanism — Researcher tier and above.
   */
  mechanismOfAction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Absorption, distribution, metabolism, excretion, half-life.
   */
  pharmacokinetics?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  researchFindings?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  administrationRoutes?:
    | {
        route?:
          | ('subcutaneous' | 'intramuscular' | 'intravenous' | 'oral' | 'intranasal' | 'transdermal' | 'topical')
          | null;
        /**
         * Bioavailability notes or considerations for this route.
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "30–60 minutes", "4 hours"
   */
  halfLife?: string | null;
  sideEffectsAndSafety?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Research-use only notices, country-specific status, FDA scheduling.
   */
  legalStatus?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Terms used to auto-fetch related studies from PubMed.
   */
  pubmedSearchTerms?:
    | {
        term?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * PubMed-synced research studies for this peptide.
   */
  studies?: (number | Study)[] | null;
  /**
   * Last time PubMed was queried for this peptide.
   */
  lastPubmedSync?: string | null;
  affiliateLinks?: (number | AffiliateLink)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-safe identifier (e.g. growth-hormone, nootropic, healing)
   */
  slug: string;
  description?: string | null;
  /**
   * Lucide icon name or emoji for UI display
   */
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studies".
 */
export interface Study {
  id: number;
  pubmedId: string;
  doi?: string | null;
  title: string;
  authors?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  journal?: string | null;
  publishedDate?: string | null;
  url?: string | null;
  abstract?: string | null;
  studyType?: ('in-vitro' | 'animal' | 'human' | 'review' | 'meta-analysis' | 'case-study') | null;
  /**
   * Editorially-summarized key takeaways from this study.
   */
  keyFindings?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Internal quality/reliability score (1–5). Used for ranking.
   */
  qualityScore?: number | null;
  peptides?: (number | Peptide)[] | null;
  syncedAt?: string | null;
  source?: ('pubmed' | 'manual') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-links".
 */
export interface AffiliateLink {
  id: number;
  partner: number | Partner;
  peptide: number | Peptide;
  /**
   * Auto-generated short code. URL will be /go/[trackingCode]
   */
  trackingCode?: string | null;
  /**
   * Partner's direct product page URL (with any UTM params they provide).
   */
  destinationUrl: string;
  isActive?: boolean | null;
  /**
   * Total clicks. Incremented by the /go/[code] redirect handler.
   */
  clicks?: number | null;
  uniqueClicks?: number | null;
  lastClickAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events".
 */
export interface ClickEvent {
  id: number;
  affiliateLink: number | AffiliateLink;
  /**
   * HTTP referrer of the click.
   */
  referrer?: string | null;
  /**
   * Country derived from IP (geo-lookup).
   */
  country?: string | null;
  deviceType?: ('desktop' | 'mobile' | 'tablet' | 'unknown') | null;
  /**
   * True if this is the first click from this session/IP for this link.
   */
  isUnique?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'peptides';
        value: number | Peptide;
      } | null)
    | ({
        relationTo: 'studies';
        value: number | Study;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'affiliate-links';
        value: number | AffiliateLink;
      } | null)
    | ({
        relationTo: 'click-events';
        value: number | ClickEvent;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  membershipTier?: T;
  membershipExpiresAt?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  partnerProfile?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "peptides_select".
 */
export interface PeptidesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  casNumber?: T;
  molecularFormula?: T;
  molecularWeight?: T;
  categories?: T;
  researchStatus?: T;
  summary?: T;
  mechanismOfAction?: T;
  pharmacokinetics?: T;
  researchFindings?: T;
  administrationRoutes?:
    | T
    | {
        route?: T;
        notes?: T;
        id?: T;
      };
  halfLife?: T;
  sideEffectsAndSafety?: T;
  legalStatus?: T;
  pubmedSearchTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  studies?: T;
  lastPubmedSync?: T;
  affiliateLinks?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studies_select".
 */
export interface StudiesSelect<T extends boolean = true> {
  pubmedId?: T;
  doi?: T;
  title?: T;
  authors?:
    | T
    | {
        name?: T;
        id?: T;
      };
  journal?: T;
  publishedDate?: T;
  url?: T;
  abstract?: T;
  studyType?: T;
  keyFindings?: T;
  qualityScore?: T;
  peptides?: T;
  syncedAt?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  website?: T;
  status?: T;
  verificationTier?: T;
  acceptedTermsAt?: T;
  commissionRate?: T;
  contactEmail?: T;
  carriedPeptides?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-links_select".
 */
export interface AffiliateLinksSelect<T extends boolean = true> {
  partner?: T;
  peptide?: T;
  trackingCode?: T;
  destinationUrl?: T;
  isActive?: T;
  clicks?: T;
  uniqueClicks?: T;
  lastClickAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events_select".
 */
export interface ClickEventsSelect<T extends boolean = true> {
  affiliateLink?: T;
  referrer?: T;
  country?: T;
  deviceType?: T;
  isUnique?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}